; PlatformIO Project Configuration File para STM32

[env:stm32_vcu]
platform = ststm32
board = nucleo_g474re
framework = arduino
monitor_speed = 115200

; Forzar C++17
build_unflags = -std=gnu++11
build_flags = 
	-std=gnu++17
    -D HAL_FDCAN_MODULE_ENABLED
	; Descomenta las siguientes 2 líneas si usas el USB nativo del STM32 (USB OTG/FS) para el Serial Monitor:
	; -D PIO_FRAMEWORK_ARDUINO_ENABLE_CDC
	; -D USBCON

; Directorios de librerías locales
lib_extra_dirs = 
	Global-Library/lib

lib_deps = 
	labfruits/Mcp320x@^1.4.2
	adafruit/Adafruit NeoPixel@^1.12.5